<a href="https://colab.research.google.com/github/Obialunamma/Python-Analysis/blob/main/Pivoting_and_unpivoting%2C_pivot_table.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [86]:
s = pd.read_csv("/content/sales_wide.csv")
s

,Region,Product,Year,January,February,March,April,May,June,July,August,September,October,November,December,TargetAnnual
0,East,Apple,2024,152,409,71,104,314,99,495,329,178,250,498,395,4678
1,East,Orange,2024,485,201,302,293,395,409,319,459,185,377,276,91,3540
2,East,Banana,2024,398,180,285,369,102,437,400,266,112,317,150,429,4059
3,East,Grape,2024,320,199,394,180,435,51,353,301,188,467,480,228,5572
4,East,Mango,2024,156,358,98,356,389,439,320,237,130,82,180,112,4183
5,West,Apple,2024,121,307,108,184,141,103,264,429,441,97,306,401,4722
6,West,Orange,2024,238,393,219,70,416,155,301,90,212,456,54,280,4819
7,West,Banana,2024,70,463,237,378,493,309,239,206,468,111,267,290,5625
8,West,Grape,2024,152,343,320,216,477,359,345,64,338,265,304,101,5729
9,West,Mango,2024,171,435,239,323,313,240,262,350,428,342,447,145,5604
10,North,Apple,2024,264,241,495,437,480,451,257,114,310,148,408,437,4597
11,North,Orange,2024,380,493,224,138,84,267,286,394,280,221,332,271,5693
12,North,Banana,2024,137,326,495,365,255,93,387,376,90,409,442,456,3795
13,North,Grape,2024,422,210,100,63,130,211,416,58,77,263,256,280,4051
14,North,Mango,2024,149,363,413,291,469,251,102,393,184,84,64,286,4643

In [87]:
s.columns

Index(['Region', 'Product', 'Year', 'January', 'February', 'March', 'April',
       'May', 'June', 'July', 'August', 'September', 'October', 'November',
       'December', 'TargetAnnual'],
      dtype='object')

In [88]:
s.isna().sum()

Region          0
Product         0
Year            0
January         0
February        0
March           0
April           0
May             0
June            0
July            0
August          0
September       0
October         0
November        0
December        0
TargetAnnual    0
dtype: int64

In [8]:
s.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15 entries, 0 to 14
Data columns (total 16 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Region        15 non-null     object
 1   Product       15 non-null     object
 2   Year          15 non-null     int64
 3   Jan           15 non-null     int64
 4   Feb           15 non-null     int64
 5   Mar           15 non-null     int64
 6   Apr           15 non-null     int64
 7   May           15 non-null     int64
 8   Jun           15 non-null     int64
 9   Jul           15 non-null     int64
 10  Aug           15 non-null     int64
 11  Sep           15 non-null     int64
 12  Oct           15 non-null     int64
 13  Nov           15 non-null     int64
 14  Dec           15 non-null     int64
 15  TargetAnnual  15 non-null     int64
dtypes: int64(14), object(2)
memory usage: 2.0+ KB

In [9]:
s.duplicated().sum()

np.int64(0)

In [89]:
m = s.melt(id_vars=["Region", "Product", "Year", "TargetAnnual"],
# value_vars=["Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"],
var_name="Month",
value_name="Sales")


print(m)

    Region Product  Year  TargetAnnual     Month  Sales
0     East   Apple  2024          4678   January    152
1     East  Orange  2024          3540   January    485
2     East  Banana  2024          4059   January    398
3     East   Grape  2024          5572   January    320
4     East   Mango  2024          4183   January    156
..     ...     ...   ...           ...       ...    ...
175  North   Apple  2024          4597  December    437
176  North  Orange  2024          5693  December    271
177  North  Banana  2024          3795  December    456
178  North   Grape  2024          4051  December    280
179  North   Mango  2024          4643  December    286

[180 rows x 6 columns]

In [83]:
m

    Region Product  Year  TargetAnnual Month  Sales
0     East   Apple  2024          4678   Jan    152
1     East  Orange  2024          3540   Jan    485
2     East  Banana  2024          4059   Jan    398
3     East   Grape  2024          5572   Jan    320
4     East   Mango  2024          4183   Jan    156
..     ...     ...   ...           ...   ...    ...
175  North   Apple  2024          4597   Dec    437
176  North  Orange  2024          5693   Dec    271
177  North  Banana  2024          3795   Dec    456
178  North   Grape  2024          4051   Dec    280
179  North   Mango  2024          4643   Dec    286

[180 rows x 6 columns]

In [23]:
print(m.to_string())

    Region Product  Year  TargetAnnual Month  Sales
0     East   Apple  2024          4678   Jan    152
1     East  Orange  2024          3540   Jan    485
2     East  Banana  2024          4059   Jan    398
3     East   Grape  2024          5572   Jan    320
4     East   Mango  2024          4183   Jan    156
5     West   Apple  2024          4722   Jan    121
6     West  Orange  2024          4819   Jan    238
7     West  Banana  2024          5625   Jan     70
8     West   Grape  2024          5729   Jan    152
9     West   Mango  2024          5604   Jan    171
10   North   Apple  2024          4597   Jan    264
11   North  Orange  2024          5693   Jan    380
12   North  Banana  2024          3795   Jan    137
13   North   Grape  2024          4051   Jan    422
14   North   Mango  2024          4643   Jan    149
15    East   Apple  2024          4678   Feb    409
16    East  Orange  2024          3540   Feb    201
17    East  Banana  2024          4059   Feb    180
18    East   Grape  2024          5572   Feb    199
19    East   Mango  2024          4183   Feb    358
20    West   Apple  2024          4722   Feb    307
21    West  Orange  2024          4819   Feb    393
22    West  Banana  2024          5625   Feb    463
23    West   Grape  2024          5729   Feb    343
24    West   Mango  2024          5604   Feb    435
25   North   Apple  2024          4597   Feb    241
26   North  Orange  2024          5693   Feb    493
27   North  Banana  2024          3795   Feb    326
28   North   Grape  2024          4051   Feb    210
29   North   Mango  2024          4643   Feb    363
30    East   Apple  2024          4678   Mar     71
31    East  Orange  2024          3540   Mar    302
32    East  Banana  2024          4059   Mar    285
33    East   Grape  2024          5572   Mar    394
34    East   Mango  2024          4183   Mar     98
35    West   Apple  2024          4722   Mar    108
36    West  Orange  2024          4819   Mar    219
37    West  Banana  2024          5625   Mar    237
38    West   Grape  2024          5729   Mar    320
39    West   Mango  2024          5604   Mar    239
40   North   Apple  2024          4597   Mar    495
41   North  Orange  2024          5693   Mar    224
42   North  Banana  2024          3795   Mar    495
43   North   Grape  2024          4051   Mar    100
44   North   Mango  2024          4643   Mar    413
45    East   Apple  2024          4678   Apr    104
46    East  Orange  2024          3540   Apr    293
47    East  Banana  2024          4059   Apr    369
48    East   Grape  2024          5572   Apr    180
49    East   Mango  2024          4183   Apr    356
50    West   Apple  2024          4722   Apr    184
51    West  Orange  2024          4819   Apr     70
52    West  Banana  2024          5625   Apr    378
53    West   Grape  2024          5729   Apr    216
54    West   Mango  2024          5604   Apr    323
55   North   Apple  2024          4597   Apr    437
56   North  Orange  2024          5693   Apr    138
57   North  Banana  2024          3795   Apr    365
58   North   Grape  2024          4051   Apr     63
59   North   Mango  2024          4643   Apr    291
60    East   Apple  2024          4678   May    314
61    East  Orange  2024          3540   May    395
62    East  Banana  2024          4059   May    102
63    East   Grape  2024          5572   May    435
64    East   Mango  2024          4183   May    389
65    West   Apple  2024          4722   May    141
66    West  Orange  2024          4819   May    416
67    West  Banana  2024          5625   May    493
68    West   Grape  2024          5729   May    477
69    West   Mango  2024          5604   May    313
70   North   Apple  2024          4597   May    480
71   North  Orange  2024          5693   May     84
72   North  Banana  2024          3795   May    255
73   North   Grape  2024          4051   May    130
74   North   Mango  2024          4643   May    469
75    East   Apple  2024          4678   Jun     99
76    East  Orange  2024          3540   Jun    409
77    East  Banana  2024          4059   Jun    437
78    East   Grape  2024          5572   Jun     51
79    East   Mango  2024          4183   Jun    439
80    West   Apple  2024          4722   Jun    103
81    West  Orange  2024          4819   Jun    155
82    West  Banana  2024          5625   Jun    309
83    West   Grape  2024          5729   Jun    359
84    West   Mango  2024          5604   Jun    240
85   North   Apple  2024          4597   Jun    451
86   North  Orange  2024          5693   Jun    267
87   North  Banana  2024          3795   Jun     93
88   North   Grape  2024          4051   Jun    211
89   North   Mango  2024          4643   Jun    251
90    East   Apple  2024          4678   Jul    495
91    East  Orange  2024          3540   Jul    319
92    East  Banana  2024          4059   Jul    400
93    East   Grape  2024          5572   Jul    353
94    East   Mango  2024          4183   Jul    320
95    West   Apple  2024          4722   Jul    264
96    West  Orange  2024          4819   Jul    301
97    West  Banana  2024          5625   Jul    239
98    West   Grape  2024          5729   Jul    345
99    West   Mango  2024          5604   Jul    262
100  North   Apple  2024          4597   Jul    257
101  North  Orange  2024          5693   Jul    286
102  North  Banana  2024          3795   Jul    387
103  North   Grape  2024          4051   Jul    416
104  North   Mango  2024          4643   Jul    102
105   East   Apple  2024          4678   Aug    329
106   East  Orange  2024          3540   Aug    459
107   East  Banana  2024          4059   Aug    266
108   East   Grape  2024          5572   Aug    301
109   East   Mango  2024          4183   Aug    237
110   West   Apple  2024          4722   Aug    429
111   West  Orange  2024          4819   Aug     90
112   West  Banana  2024          5625   Aug    206
113   West   Grape  2024          5729   Aug     64
114   West   Mango  2024          5604   Aug    350
115  North   Apple  2024          4597   Aug    114
116  North  Orange  2024          5693   Aug    394
117  North  Banana  2024          3795   Aug    376
118  North   Grape  2024          4051   Aug     58
119  North   Mango  2024          4643   Aug    393
120   East   Apple  2024          4678   Sep    178
121   East  Orange  2024          3540   Sep    185
122   East  Banana  2024          4059   Sep    112
123   East   Grape  2024          5572   Sep    188
124   East   Mango  2024          4183   Sep    130
125   West   Apple  2024          4722   Sep    441
126   West  Orange  2024          4819   Sep    212
127   West  Banana  2024          5625   Sep    468
128   West   Grape  2024          5729   Sep    338
129   West   Mango  2024          5604   Sep    428
130  North   Apple  2024          4597   Sep    310
131  North  Orange  2024          5693   Sep    280
132  North  Banana  2024          3795   Sep     90
133  North   Grape  2024          4051   Sep     77
134  North   Mango  2024          4643   Sep    184
135   East   Apple  2024          4678   Oct    250
136   East  Orange  2024          3540   Oct    377
137   East  Banana  2024          4059   Oct    317
138   East   Grape  2024          5572   Oct    467
139   East   Mango  2024          4183   Oct     82
140   West   Apple  2024          4722   Oct     97
141   West  Orange  2024          4819   Oct    456
142   West  Banana  2024          5625   Oct    111
143   West   Grape  2024          5729   Oct    265
144   West   Mango  2024          5604   Oct    342
145  North   Apple  2024          4597   Oct    148
146  North  Orange  2024          5693   Oct    221
147  North  Banana  2024          3795   Oct    409
148  North   Grape  2024          4051   Oct    263
149  North   Mango  2024          4643   Oct     84
150   East   Apple  2024          4678   Nov    498
151   East  Orange  2024          3540   Nov    276
152   East  Banana  2024          4059   Nov    150
153   East   Grape  2024          5572   Nov    480
154   East   Mango  2024          4183   Nov    180
155   West   Apple  2024          4722   Nov    306
156   West  Orange  2024          4819   Nov     54
157   West  Banana  2024          5625   Nov    267
158   West   Grape  2024          5729   Nov    304
159   West   Mango  2024          5604   Nov    447
160  North   Apple  2024          4597   Nov    408
161  North  Orange  2024          5693   Nov    332
162  North  Banana  2024          3795   Nov    442
163  North   Grape  2024          4051   Nov    256
164  North   Mango  2024          4643   Nov     64
165   East   Apple  2024          4678   Dec    395
166   East  Orange  2024          3540   Dec     91
167   East  Banana  2024          4059   Dec    429
168   East   Grape  2024          5572   Dec    228
169   East   Mango  2024          4183   Dec    112
170   West   Apple  2024          4722   Dec    401
171   West  Orange  2024          4819   Dec    280
172   West  Banana  2024          5625   Dec    290
173   West   Grape  2024          5729   Dec    101
174   West   Mango  2024          5604   Dec    145
175  North   Apple  2024          4597   Dec    437
176  North  Orange  2024          5693   Dec    271
177  North  Banana  2024          3795   Dec    456
178  North   Grape  2024          4051   Dec    280
179  North   Mango  2024          4643   Dec    286

In [25]:
p = pd.read_csv("/content/PQ Exercise 1d.csv")
p

,Metric,Store,Cat,01/01/2017,02/01/2017,03/01/2017,Q1 2017,04/01/2017,05/01/2017,06/01/2017,...,Q2 2018,07/01/2018,08/01/2018,09/01/2018,Q3 2018,10/01/2018,11/01/2018,12/01/2018,Q4 2018,2018
0,Sales,1,1,NaN,NaN,NaN,NaN,19403.5400,21827.9000,21043.3900,...,62274.8300,22136.6400,26229.2100,57258.4300,105624.2800,42960.9100,17596.9600,16145.3500,76703.2200,357161.8700
1,NaN,1,2,50605.2700,44682.7400,47928.8900,143216.9000,44292.8700,48397.9800,43751.9400,...,136442.7900,43615.4900,41892.5500,47450.5000,132958.5400,46549.7300,45025.0200,44418.1100,135992.8600,548611.0900
2,NaN,1,3,13740.1200,10887.8400,11523.4700,36151.4300,11135.1700,12275.5800,10123.4500,...,33534.2000,9001.3700,10366.8500,11157.0800,30525.3000,10179.2900,9226.8000,8868.9300,28275.0200,128485.9500
3,NaN,1,4,39954.0400,35351.2100,36826.9500,112132.2000,34660.1600,38086.1900,32668.6700,...,105415.0200,34118.1100,33872.0700,37809.4900,105799.6700,36174.4300,34740.1900,33806.7100,104721.3300,428068.2200
4,NaN,2,1,35034.0600,60483.7000,58221.5200,153739.2800,25962.3200,27372.0500,28660.8700,...,81995.2400,28446.9200,32213.9900,82766.0700,143426.9800,66560.0000,21308.5900,22163.1200,110031.7100,489193.2100
5,NaN,2,2,74661.1600,65487.4600,70853.5800,211002.2000,64963.9000,68428.6400,66622.0300,...,200014.5700,64307.0100,59770.1800,68286.2000,192363.3900,64295.2200,65172.2000,66471.8600,195939.2800,799319.4400
6,NaN,2,3,16873.2000,13821.0100,14607.2800,45301.4900,15635.9500,14895.9600,13061.5600,...,43593.4700,10394.2800,12406.4400,13404.2300,36204.9500,12873.0900,11547.5000,11862.2600,36282.8500,161382.7600
7,NaN,2,4,47681.9600,44197.9500,46131.1400,138011.0500,42126.7100,46937.8100,42489.2100,...,131553.7300,44622.5600,41455.3400,47951.7600,134029.6600,45280.8900,43463.5500,43703.7600,132448.2000,536042.6400
8,Margin,1,1,NaN,NaN,NaN,NaN,0.5432,0.5432,0.5432,...,0.5432,0.5432,0.5432,0.5432,0.5432,0.5432,0.5432,0.5432,0.5432,0.5432
9,NaN,1,2,0.5542,0.5542,0.5542,0.5542,0.5542,0.5542,0.5542,...,0.5542,0.5542,0.5542,0.5542,0.5542,0.5542,0.5542,0.5542,0.5542,0.5542
10,NaN,1,3,0.5212,0.5212,0.5212,0.5212,0.5212,0.5212,0.5212,...,0.5212,0.5212,0.5212,0.5212,0.5212,0.5212,0.5212,0.5212,0.5212,0.5212
11,NaN,1,4,0.5462,0.5462,0.5462,0.5462,0.5462,0.5462,0.5462,...,0.5462,0.5462,0.5462,0.5462,0.5462,0.5462,0.5462,0.5462,0.5462,0.5462
12,NaN,2,1,0.5432,0.5432,0.5432,0.5432,0.5432,0.5432,0.5432,...,0.5432,0.5432,0.5432,0.5432,0.5432,0.5432,0.5432,0.5432,0.5432,0.5432
13,NaN,2,2,0.5542,0.5542,0.5542,0.5542,0.5542,0.5542,0.5542,...,0.5542,0.5542,0.5542,0.5542,0.5542,0.5542,0.5542,0.5542,0.5542,0.5542
14,NaN,2,3,0.5212,0.5212,0.5212,0.5212,0.5212,0.5212,0.5212,...,0.5212,0.5212,0.5212,0.5212,0.5212,0.5212,0.5212,0.5212,0.5212,0.5212
15,NaN,2,4,0.5462,0.5462,0.5462,0.5462,0.5462,0.5462,0.5462,...,0.5462,0.5462,0.5462,0.5462,0.5462,0.5462,0.5462,0.5462,0.5462,0.5462

In [30]:
p = p.melt(id_vars=["Metric",	"Store",	"Cat"],
    var_name="Date",
    value_name="Sales")

print(p)

    Metric  Store  Cat        Date       Sales
0    Sales      1    1  01/01/2017         NaN
1      NaN      1    2  01/01/2017  50605.2700
2      NaN      1    3  01/01/2017  13740.1200
3      NaN      1    4  01/01/2017  39954.0400
4      NaN      2    1  01/01/2017  35034.0600
..     ...    ...  ...         ...         ...
539    NaN      1    4        2018      0.5462
540    NaN      2    1        2018      0.5432
541    NaN      2    2        2018      0.5542
542    NaN      2    3        2018      0.5212
543    NaN      2    4        2018      0.5462

[544 rows x 5 columns]

In [31]:
# Fill down the Metric column
p['Metric'] = p['Metric'].ffill()

In [ ]:
print(p.to_string())

In [41]:
p.head()

  Metric  Store  Cat        Date     Sales
0  Sales      1    1  01/01/2017       NaN
1  Sales      1    2  01/01/2017  50605.27
2  Sales      1    3  01/01/2017  13740.12
3  Sales      1    4  01/01/2017  39954.04
4  Sales      2    1  01/01/2017  35034.06

In [44]:
v = p.pivot(index=['Store', 'Cat', 'Date'], columns='Metric', values='Sales')
v

Metric                Margin      Sales
Store Cat Date
1     1   01/01/2017     NaN        NaN
          01/01/2018  0.5432   24924.50
          02/01/2017     NaN        NaN
          02/01/2018  0.5432   46039.49
          03/01/2017     NaN        NaN
...                      ...        ...
2     4   Q2 2018     0.5462  131553.73
          Q3 2017     0.5462  134029.66
          Q3 2018     0.5462  134029.66
          Q4 2017     0.5462  132448.20
          Q4 2018     0.5462  132448.20

[272 rows x 2 columns]

In [47]:
v.columns.name =None

In [50]:
v.reset_index(inplace=True)

In [51]:
v

     Store  Cat        Date  Margin      Sales
0        1    1  01/01/2017     NaN        NaN
1        1    1  01/01/2018  0.5432   24924.50
2        1    1  02/01/2017     NaN        NaN
3        1    1  02/01/2018  0.5432   46039.49
4        1    1  03/01/2017     NaN        NaN
..     ...  ...         ...     ...        ...
267      2    4     Q2 2018  0.5462  131553.73
268      2    4     Q3 2017  0.5462  134029.66
269      2    4     Q3 2018  0.5462  134029.66
270      2    4     Q4 2017  0.5462  132448.20
271      2    4     Q4 2018  0.5462  132448.20

[272 rows x 5 columns]

error =

raise → complain and stop.

ignore → leave bad values untouched.

coerce → force conversion, replace bad ones with NaT/NaN.

In [61]:
pd.to_datetime(v['Date'], errors='coerce', format='mixed')

0     2017-01-01
1     2018-01-01
2     2017-02-01
3     2018-02-01
4     2017-03-01
         ...
267          NaT
268          NaT
269          NaT
270          NaT
271          NaT
Name: Date, Length: 272, dtype: datetime64[ns]

In [62]:
# errors="coerce" = "try to convert; if it fails, don’t crash, just put NaT".
v['Date'] = pd.to_datetime(v['Date'], errors='coerce', format='mixed')

In [63]:
v.head()

   Store  Cat       Date  Margin     Sales
0      1    1 2017-01-01     NaN       NaN
1      1    1 2018-01-01  0.5432  24924.50
2      1    1 2017-02-01     NaN       NaN
3      1    1 2018-02-01  0.5432  46039.49
4      1    1 2017-03-01     NaN       NaN

In [65]:
v.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 272 entries, 0 to 271
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Store   272 non-null    int64
 1   Cat     272 non-null    int64
 2   Date    208 non-null    datetime64[ns]
 3   Margin  268 non-null    float64
 4   Sales   268 non-null    float64
dtypes: datetime64[ns](1), float64(2), int64(2)
memory usage: 10.8 KB

In [72]:
v.dropna(inplace = True)

In [74]:
v.info()

<class 'pandas.core.frame.DataFrame'>
Index: 205 entries, 1 to 263
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Store   205 non-null    int64
 1   Cat     205 non-null    int64
 2   Date    205 non-null    datetime64[ns]
 3   Margin  205 non-null    float64
 4   Sales   205 non-null    float64
dtypes: datetime64[ns](1), float64(2), int64(2)
memory usage: 9.6 KB

In [75]:
v.isna().any()

Store     False
Cat       False
Date      False
Margin    False
Sales     False
dtype: bool

In [77]:
v.reset_index(drop=True)

     Store  Cat       Date  Margin      Sales
0        1    1 2018-01-01  0.5432   24924.50
1        1    1 2018-02-01  0.5432   46039.49
2        1    1 2018-03-01  0.5432   41595.55
3        1    1 2017-04-01  0.5432   19403.54
4        1    1 2018-04-01  0.5432   19403.54
..     ...  ...        ...     ...        ...
200      2    4 2018-11-01  0.5462   43463.55
201      2    4 2017-12-01  0.5462   43703.76
202      2    4 2018-12-01  0.5462   43703.76
203      2    4 2017-01-01  0.5462  536042.64
204      2    4 2018-01-01  0.5462  536042.64

[205 rows x 5 columns]

In [157]:
v["Profit"] = round((v["Margin"] * v["Sales"]),2)
v["Profit"]

1       13538.99
3       25008.65
5       22594.70
6       10540.00
7       10540.00
         ...
259     23739.79
260     23870.99
261     23870.99
262    292786.49
263    292786.49
Name: Profit, Length: 205, dtype: float64

In [156]:
(v.Margin * v.Sales).round(2)

1       13538.99
3       25008.65
5       22594.70
6       10540.00
7       10540.00
         ...
259     23739.79
260     23870.99
261     23870.99
262    292786.49
263    292786.49
Length: 205, dtype: float64

In [80]:
v.rename(columns= {'Cat': 'Category'}, inplace = True)

In [81]:
v['Month'] = v['Date'].dt.month_name()

In [82]:
v

     Store  Category       Date  Margin      Sales     Profit     Month
1        1         1 2018-01-01  0.5432   24924.50   13538.99   January
3        1         1 2018-02-01  0.5432   46039.49   25008.65  February
5        1         1 2018-03-01  0.5432   41595.55   22594.70     March
6        1         1 2017-04-01  0.5432   19403.54   10540.00     April
7        1         1 2018-04-01  0.5432   19403.54   10540.00     April
..     ...       ...        ...     ...        ...        ...       ...
259      2         4 2018-11-01  0.5462   43463.55   23739.79  November
260      2         4 2017-12-01  0.5462   43703.76   23870.99  December
261      2         4 2018-12-01  0.5462   43703.76   23870.99  December
262      2         4 2017-01-01  0.5462  536042.64  292786.49   January
263      2         4 2018-01-01  0.5462  536042.64  292786.49   January

[205 rows x 7 columns]

In [91]:
m.drop(columns=['Year'])
m.drop('Year', axis = 1)

    Region Product  TargetAnnual     Month  Sales
0     East   Apple          4678   January    152
1     East  Orange          3540   January    485
2     East  Banana          4059   January    398
3     East   Grape          5572   January    320
4     East   Mango          4183   January    156
..     ...     ...           ...       ...    ...
175  North   Apple          4597  December    437
176  North  Orange          5693  December    271
177  North  Banana          3795  December    456
178  North   Grape          4051  December    280
179  North   Mango          4643  December    286

[180 rows x 5 columns]

In [104]:
t = m.groupby(["Region", "Product"]).agg({"Sales": "sum", "TargetAnnual": "first"})
t

                Sales  TargetAnnual
Region Product
East   Apple     3294          4678
       Banana    3445          4059
       Grape     3596          5572
       Mango     2857          4183
       Orange    3792          3540
North  Apple     4042          4597
       Banana    3831          3795
       Grape     2486          4051
       Mango     3049          4643
       Orange    3370          5693
West   Apple     2902          4722
       Banana    3531          5625
       Grape     3284          5729
       Mango     3695          5604
       Orange    2884          4819

In [107]:
T = m.groupby(["Region", "Product"], as_index=False).agg({"Sales": "sum", "TargetAnnual": "mean"})
T

   Region Product  Sales  TargetAnnual
0    East   Apple   3294          4678
1    East  Banana   3445          4059
2    East   Grape   3596          5572
3    East   Mango   2857          4183
4    East  Orange   3792          3540
5   North   Apple   4042          4597
6   North  Banana   3831          3795
7   North   Grape   2486          4051
8   North   Mango   3049          4643
9   North  Orange   3370          5693
10   West   Apple   2902          4722
11   West  Banana   3531          5625
12   West   Grape   3284          5729
13   West   Mango   3695          5604
14   West  Orange   2884          4819

In [116]:
t["Achieved"] = t["Sales"] >= t["TargetAnnual"]
t["Difference"] = t["Sales"] - t["TargetAnnual"]

print(t)

                Sales  TargetAnnual  Achieved  Difference
Region Product
East   Apple     3294          4678     False       -1384
       Banana    3445          4059     False        -614
       Grape     3596          5572     False       -1976
       Mango     2857          4183     False       -1326
       Orange    3792          3540      True         252
North  Apple     4042          4597     False        -555
       Banana    3831          3795      True          36
       Grape     2486          4051     False       -1565
       Mango     3049          4643     False       -1594
       Orange    3370          5693     False       -2323
West   Apple     2902          4722     False       -1820
       Banana    3531          5625     False       -2094
       Grape     3284          5729     False       -2445
       Mango     3695          5604     False       -1909
       Orange    2884          4819     False       -1935

In [112]:
t.Achieved.value_counts()

Achieved
False    13
True      2
Name: count, dtype: int64

In [117]:
print(sum(t.TargetAnnual))
print(sum(t.Sales))
print(sum(t.TargetAnnual) - sum(t.Sales))

71310
50058
21252

In [118]:
print(f"{sum(t.TargetAnnual):,}")
print(f"{sum(t.Sales):,}")
print(f"{sum(t.TargetAnnual) - sum(t.Sales):,}")

71,310
50,058
21,252

In [123]:
i = m.pivot_table(index=["Region", "Product"], values=["Sales", "TargetAnnual"],aggfunc={"Sales": "sum", "TargetAnnual": "first"}) #.reset_index()
i

                Sales  TargetAnnual
Region Product
East   Apple     3294          4678
       Banana    3445          4059
       Grape     3596          5572
       Mango     2857          4183
       Orange    3792          3540
North  Apple     4042          4597
       Banana    3831          3795
       Grape     2486          4051
       Mango     3049          4643
       Orange    3370          5693
West   Apple     2902          4722
       Banana    3531          5625
       Grape     3284          5729
       Mango     3695          5604
       Orange    2884          4819

In [126]:
i["Achieved"] = i["Sales"] >= i["TargetAnnual"]
i["Difference"] = i["Sales"] - i["TargetAnnual"]
i

                Sales  TargetAnnual  Achieved  Difference
Region Product
East   Apple     3294          4678     False       -1384
       Banana    3445          4059     False        -614
       Grape     3596          5572     False       -1976
       Mango     2857          4183     False       -1326
       Orange    3792          3540      True         252
North  Apple     4042          4597     False        -555
       Banana    3831          3795      True          36
       Grape     2486          4051     False       -1565
       Mango     3049          4643     False       -1594
       Orange    3370          5693     False       -2323
West   Apple     2902          4722     False       -1820
       Banana    3531          5625     False       -2094
       Grape     3284          5729     False       -2445
       Mango     3695          5604     False       -1909
       Orange    2884          4819     False       -1935

In [135]:
m.pivot_table(index = ['Month'], values=['Sales'], aggfunc='sum').sort_values(by='Sales', ascending=False)

           Sales
Month
February    4921
May         4893
July        4746
November    4464
December    4202
August      4066
March       4000
October     3889
June        3874
April       3767
September   3621
January     3615

In [144]:
v.pivot_table(index = ['Month'], values=['Profit'], aggfunc='sum').sort_values(by='Profit', ascending=False)

               Profit
Month
January    4086970.39
September   399693.46
October     354855.64
March       335367.14
February    325486.79
May         304145.28
June        282607.76
August      282202.20
April       282173.86
July        280809.58
November    271494.50
December    270811.40

In [142]:
v.groupby("Month")["Profit"].sum().sort_values(ascending=False)

Month
January      4086970.39
September     399693.46
October       354855.64
March         335367.14
February      325486.79
May           304145.28
June          282607.76
August        282202.20
April         282173.86
July          280809.58
November      271494.50
December      270811.40
Name: Profit, dtype: float64

In [ ]:
v.pivot_table(index = ['Store', 'Month'], values=['Profit'], aggfunc=['sum', 'mean']).round(2)

In [150]:
v.groupby(['Store', 'Month']).agg({'Profit': ['sum', 'mean'], 'Sales': ['sum']}).round(2)

                     Profit                  Sales
                        sum       mean         sum
Store Month
1     April       119644.28   14955.54   218983.48
      August      122737.36   15342.17   224721.36
      December    112948.78   14118.60   206478.20
      February    124502.13   17786.02   227883.07
      January    1725255.05  115017.00  3158177.62
      July        119046.28   14880.78   217743.22
      June        117596.14   14699.52   215174.90
      March       127960.90   18280.13   234154.17
      May         131759.58   16469.95   241175.30
      November    116591.28   14573.91   213177.94
      October     148396.30   18549.54   271728.72
      September   167732.92   20966.61   307351.00
2     April       162529.58   20316.20   297377.76
      August      159464.84   19933.10   291691.90
      December    157862.62   19732.83   288402.00
      February    200984.66   25123.08   367980.24
      January    2361715.34  147607.21  4320376.86
      July        161763.30   20220.41   295541.54
      June        165011.62   20626.45   301667.34
      March       207406.24   25925.78   379627.04
      May         172385.70   21548.21   315268.92
      November    154903.22   19362.90   282983.68
      October     206459.34   25807.42   378018.40
      September   231960.54   28995.07   424816.52

    Region Product  TargetAnnual     Month  Sales
0     East   Apple          4678   January    152
1     East  Orange          3540   January    485
2     East  Banana          4059   January    398
3     East   Grape          5572   January    320
4     East   Mango          4183   January    156
..     ...     ...           ...       ...    ...
175  North   Apple          4597  December    437
176  North  Orange          5693  December    271
177  North  Banana          3795  December    456
178  North   Grape          4051  December    280
179  North   Mango          4643  December    286

[180 rows x 5 columns]